### ISSUE TITLE
URLs are marked as invalid if they are missing the proceeding `http://` or `https://`

### ISSUE THREAD

**Issue by jamiehewitt15** [sindresorhus/is-url-superb#11]
URLs are marked as invalid if they are missing the proceeding `http://` or `https://`

A lot of users enter URLs without  the proceeding `http://` or `https://` e.g. www.example.com. It would be very useful if these URLs could be marked as valid

**Comment by sindresorhus** [comment]
I don't think it should accept that by default, but I agree there could be a `lenient` option. When true, it could pass the input through https://github.com/sindresorhus/prepend-http first.

**Comment by jamiehewitt15** [comment]
Yeah true, it would be good as an option
