### ISSUE TITLE
could you change 【try {}catch{}】to 【try {} catch(e) {}】?

### ISSUE THREAD

**Issue by hongrunhui** [sindresorhus/is-url-superb#13]
![2a8228e709d662ed9f244b4a6731d97b](https://user-images.githubusercontent.com/9162319/145561778-8ba50e34-b7c0-4a70-af1c-ed02804cf25b.png)

**Comment by hongrunhui** [comment]
因为少了个括号，10.12系统不支持

**Comment by hongrunhui** [comment]
mac

**Comment by hongrunhui** [comment]
10.12 is not supported because of missing parentheses

**Comment by sindresorhus** [comment]
You need a newer Node.js version.

**Comment by hongrunhui** [comment]
It's running in browser(macos 10.12 version ) env

**Comment by hongrunhui** [comment]
just add a () after [catch]
so Mone your little hand （动动你的小手😁）
