### ISSUE TITLE
isUrl('https://www') returns true (as does any https://xyz)

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [sindresorhus/is-url-superb#14]
Same for the http variant. Technically, this isn't an issue with your package since for some reason the `URL` constructor allows you to create URLs like `https://xyz` even though they're missing the TLD.

Is this working as expected? If not, where would I file an issue for something like this that's built into JS?

**Comment by sindresorhus** [comment]
Those are valid URLs. A TLD is only required for public URLs.

> TLD-less URLs (Top-Level Domain-less URLs) are URLs that don't have a top-level domain like .com, .org, etc. They're often used in local network environments. For example, http://webserver/ could resolve to a local web server within a corporate network.

**Comment by AleksandrHovhannisyan** [comment]
Oh I see, thanks for clarifying
