### ISSUE TITLE
Bug: passes validation even though incorrect url

### ISSUE THREAD

**Issue by heymartinadams** [sindresorhus/is-url-superb#3]
Using `v2.0.0`

Any url that contains `//` + `domain` appears to pass validation. However, if you prefix a colon `:`, you can now add any string before `://` + `domain`, and the test will still pass as a valid url.

**Passes as valid url:**
`//google.com`
`sdlkjasdfoiklnsadf://google.com`

**Comment by sindresorhus** [comment]
Both of those are valid URLs:

1. Protocol-relative URL.
2. URL with a custom protocol.

**Comment by heymartinadams** [comment]
Gotcha, thanks for the clarification, @sindresorhus.
