### ISSUE TITLE
we missed one pattern, news:

### ISSUE THREAD

**Issue by revelt** [sindresorhus/is-url-superb#5]
I was doing checks against all examples of URI's given in https://www.ietf.org/rfc/rfc2396.txt and noticed their example, `news:comp.infosystems.www.servers.unix` is reported wrongly.

Do you think it's worth to supplement the regex with `news:`?

**Comment by sindresorhus** [comment]
Sure

**Comment by revelt** [comment]
Waait, we're using `url-regex`, there's nothing to do here, let's raise an issue there instead.
