### ISSUE TITLE
Protocol Relative URLs Are Valid

### ISSUE THREAD

**Issue by shellscape** [sindresorhus/is-url-superb#6]
So a sticky point from the 4.0.0: protocol relative urls are still valid urls. 

Using this css:

```css
https://jigsaw.w3.org/css-validator/#validate_by_input
```

And this validator: https://jigsaw.w3.org/css-validator/#validate_by_input

If a url is considered valid in css, should it not also be considered valid in the node realm? I understand that this was removed with the nuking of url-regex due to a vulnerability in that package. I'm not sure that this isn't a regression that's been introduced as a result though. Removing that capability makes the package's function, dare I say, _less than superb_. 😄

**Comment by sindresorhus** [comment]
Did you mean to use a protocol-relative example? Because the URL above is not a normal URL.

Dropping support for it was an intentional choice as it's an anti-pattern now: https://twitter.com/paul_irish/status/588502455530311680

**Comment by shellscape** [comment]
Copypasta got the better of me. I've updated the snippet with the CSS to validate. Regardless of it being considered an antipattern by a single vendor, it's still perfectly valid. Until the CSS spec is updated to say otherwise, it'll continue to be valid and supported by vendors that support the spec.

**Comment by davilima6** [comment]
@sindresorhus, I see your point but could we consider the change in a context of a transitory phase (versions) where protocol-relative URLs trigger a deprecation warning but are still supported?

**Comment by sindresorhus** [comment]
No, this package is no longer using the dependency that allowed protocol-relative URLs. The change was done in a major release, so it should be fine.
