### ISSUE TITLE
Literal spaces after path are valid URLs

### ISSUE THREAD

**Issue by brandon93s** [sindresorhus/is-url-superb#7]
Documenting an edge case for future users:  if a sentence starts with a URL and contains a path, any literal spaces are considered valid and the full sentence will be considered a valid URL. This is technically a valid URL which your browser will encode for you upon navigation.  The `URL` implementation allows for it as unencoded input.

```js
const isUrl = require('is-url-superb')
isUrl('https://github.com/sindresorhus/is-url-superb is the repo for an npm package to validate URLs.')
// => true
```

**Comment by sindresorhus** [comment]
Maybe we should do a check here for whether there are any unescaped spaces and if so return `false`?

**Comment by brandon93s** [comment]
I support that as I believe it to be a more intuitive behavior even if it's a deviation from the `URL` implementation.  Glad to open a quick PR.

**Comment by sindresorhus** [comment]
PR welcome
